namespace ProjectRoulette
{
	public static class GlobalValue
	{
		// Google Spread Sheet
		public static readonly string DataInstanceName = "Name";
		public static readonly string IgnorePrefix = "#";

		// File Path
		public static readonly string SOpath = "Assets/Resources/SO/AutoGenerated";
		public static readonly string ScriptPath = "Assets/Scripts/AutoGenerated";

		// Roulette
		public static readonly int SlotRowCount = 5; // 룰렛 세로 수
		public static readonly int SlotColCount = 5; // 룰렛 가로 수

		// Probability
		public static readonly int ProbabilityMaxCount = 1000; // 확률 계산 기준 정수
	}
}
