using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace ProjectRoulette
{
	public class DataManager
	{
		private Dictionary<EItem, ItemData> _itemData = new Dictionary<EItem, ItemData>();
		private Dictionary<ESymbolData, SymbolData> _symbolData = new Dictionary<ESymbolData, SymbolData>();
		private GlobalValueData _globalValueData;

		private readonly string SO_PATH = "Assets/Resources/SO/AutoGenerated";

		public void Init()
		{
			// Load Data
			var itemData = Resources.LoadAll<ItemData>(SO_PATH);
			var symbolData = Resources.LoadAll<SymbolData>(SO_PATH);
			var globalValueData = Resources.Load<GlobalValueData>(SO_PATH);
			
			// Cache Data
			for (var i = 1; i < (int)EItem.Max; i++)
			{
				_itemData[(EItem)i] = itemData.FirstOrDefault(x => x.Key == i);
			}
			
			for (var i = 1; i < (int)ESymbolData.Max; i++)
			{
				_symbolData[(ESymbolData)i] = symbolData.FirstOrDefault(x => x.Key == i);
			}
			
			_globalValueData = globalValueData;
		}

		public ItemData GetItemData(EItem item) => _itemData[item];
		public SymbolData GetSymbolData(ESymbolData symbolData) => _symbolData[symbolData];
		public GlobalValueData GetGlobalValueData() => _globalValueData;
	}
}
